---
### Base packages

- name: standard packeges
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - mc
    - vim
    - unzip
    - zip
    - sysstat
    - wget
    - curl
    - tmux
    - net-tools
    - open-vm-tools
    - mutt
    - postfix
    - bind-utils

# vi: set expandtab:
